"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";

import { FallingLeaves } from "./FallingLeaves";

interface Fact {
  icon: string;
  title: string;
  message: string;
  from: string;
  to: string;
  accent: string;
}

/* Real fix, 2026-08-11: every fact used to cycle through an unrelated hue
   (blue, red, purple, amber...) — meaning a passerby glancing at the kiosk
   at a random moment would just as likely see red or blue as green,
   directly contradicting docs/planning/02-design-mandate.md SS4.5's
   explicit "Green + White is the base... the identity a person should
   recognize the kiosk by from across a room" rule. This wasn't about
   darkness (the deck's own screens use solid dark-forest-green full-bleed
   heroes) — it was the color *variety*. All 12 facts now stay within the
   eco-green family; volt-amber and bloom-violet still appear as real,
   deliberate accents (the "Free Charging" and "Sort It Right" facts) per
   SS2, not as a whole competing hue. */
const FACTS: Fact[] = [
  {
    icon: "🍶",
    title: "450 Years",
    message: "A plastic bottle takes 450 years to fully decompose in nature.",
    from: "#0A2E0F",
    to: "#1B5E20",
    accent: "#4ADE80",
  },
  {
    icon: "🌊",
    title: "8 Million Tons",
    message: "Plastic waste enters our oceans every single year worldwide.",
    from: "#0A2E2B",
    to: "#0D5C56",
    accent: "#5EEAD4",
  },
  {
    icon: "♻️",
    title: "Only 9%",
    message: "Of all plastic ever produced has actually been recycled.",
    from: "#051A08",
    to: "#166534",
    accent: "#86EFAC",
  },
  {
    icon: "⚡",
    title: "Free Charging",
    message: "Drop a bottle here. Earn credits. Charge your phone — for free.",
    from: "#14330E",
    to: "#3F6212",
    accent: "#FCD34D",
  },
  {
    icon: "🌍",
    title: "163 Million",
    message: "Plastic pieces generated by Filipinos every single day.",
    from: "#0A2E0F",
    to: "#14532D",
    accent: "#BEF264",
  },
  {
    icon: "💡",
    title: "Sort It Right",
    message:
      "Clean your plastic before disposal — dirty plastic goes to landfill.",
    from: "#132E1C",
    to: "#1B5E20",
    accent: "#C4B5FD",
  },
  {
    icon: "🏭",
    title: "88% Less Energy",
    message:
      "Recycling plastic uses 88% less energy than making it from scratch.",
    from: "#0A2E2B",
    to: "#0F766E",
    accent: "#5EEAD4",
  },
  {
    icon: "🐠",
    title: "Marine Life",
    message: "Over 1 million marine animals die from plastic pollution yearly.",
    from: "#0A2E2B",
    to: "#166534",
    accent: "#6EE7B7",
  },
  {
    icon: "🗑️",
    title: "Segregate Waste",
    message: "Separate plastic, paper, glass, and organic waste at home.",
    from: "#1B5E20",
    to: "#3F6212",
    accent: "#FDE68A",
  },
  {
    icon: "🔋",
    title: "4 Chargers",
    message: "EcoCharge supports up to 4 simultaneous phone charging sessions.",
    from: "#051A08",
    to: "#14532D",
    accent: "#4ADE80",
  },
  {
    icon: "🌱",
    title: "Start Small",
    message: "One bottle today. One habit formed. A cleaner future ahead.",
    from: "#0A2E0F",
    to: "#1A5C16",
    accent: "#86EFAC",
  },
  {
    icon: "🤝",
    title: "Together",
    message:
      "EcoCharge turns your plastic waste into clean energy for everyone.",
    from: "#142B0A",
    to: "#2E6B14",
    accent: "#BEF264",
  },
];

const TRANSITIONS = [
  "idle-slide-left",
  "idle-slide-up",
  "idle-fade",
  "idle-zoom",
  "idle-flip",
];

export function IdleScreen({ onDismiss }: { onDismiss: () => void }) {
  const [index, setIndex] = useState(0);
  const [transition, setTransition] = useState("idle-fade");
  const [key, setKey] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const advance = useCallback(() => {
    const next = TRANSITIONS[Math.floor(Math.random() * TRANSITIONS.length)];

    setTransition(next);
    setIndex((prev) => (prev + 1) % FACTS.length);
    setKey((prev) => prev + 1);
  }, []);

  useEffect(() => {
    timerRef.current = setInterval(advance, 3000);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [advance]);

  const fact = FACTS[index];

  return (
    <div
      role="button"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 50,
        cursor: "pointer",
        background: `linear-gradient(155deg, ${fact.from}, ${fact.to})`,
        transition: "background 0.8s ease",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "32px 28px",
      }}
      tabIndex={0}
      onClick={onDismiss}
      onKeyDown={(e) => e.key === "Enter" && advance()}
    >
      {/* dot grid overlay */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          opacity: 0.04,
          backgroundImage:
            "radial-gradient(circle, white 1px, transparent 1px)",
          backgroundSize: "28px 28px",
          pointerEvents: "none",
        }}
      />

      <FallingLeaves />

      {/*
       * Mascot — a welcoming presence on the attract screen, per
       * docs/planning/02-design-mandate.md SS4.6 ("the idle/attract loop —
       * a natural home for character personality"). Anchored bottom-right,
       * partially off-frame, so it reads as a companion peeking in rather
       * than competing with the rotating fact card for attention. Credit:
       * public/mascot/CREDITS.md.
       */}
      <div
        aria-hidden
        className="float-anim"
        style={{
          position: "absolute",
          bottom: -20,
          right: -30,
          width: "58vmin",
          maxWidth: 420,
          opacity: 0.92,
          pointerEvents: "none",
          filter: "drop-shadow(0 12px 28px rgba(0,0,0,0.35))",
        }}
      >
        <Image
          alt=""
          height={1000}
          src="/mascot/attract-hero.png"
          style={{ width: "100%", height: "auto" }}
          width={936}
        />
      </div>

      {/* EcoCharge brand */}
      <div
        style={{
          position: "absolute",
          top: 32,
          left: 28,
          display: "flex",
          alignItems: "center",
          gap: 8,
        }}
      >
        <span style={{ fontSize: 18 }}>🌿</span>
        <span
          style={{
            color: "rgba(255,255,255,0.45)",
            fontWeight: 700,
            fontSize: 13,
            letterSpacing: "0.05em",
          }}
        >
          EcoCharge
        </span>
      </div>

      {/* progress dots */}
      <div style={{ position: "absolute", top: 36, display: "flex", gap: 5 }}>
        {FACTS.map((_, i) => (
          <div
            key={i}
            style={{
              width: i === index ? 22 : 5,
              height: 5,
              borderRadius: 3,
              background: i === index ? fact.accent : "rgba(255,255,255,0.25)",
              transition: "all 0.35s ease",
            }}
          />
        ))}
      </div>

      {/* fact card */}
      <div
        key={key}
        className={transition}
        style={{
          textAlign: "center",
          maxWidth: 340,
          position: "relative",
          zIndex: 1,
        }}
      >
        <div
          className="float-anim"
          style={{
            fontSize: 88,
            marginBottom: 28,
            display: "inline-block",
            filter: "drop-shadow(0 4px 16px rgba(0,0,0,0.4))",
          }}
        >
          {fact.icon}
        </div>

        <h2
          style={{
            color: fact.accent,
            fontSize: 38,
            fontWeight: 800,
            letterSpacing: "-0.02em",
            marginBottom: 14,
            lineHeight: 1.1,
          }}
        >
          {fact.title}
        </h2>

        <p
          style={{
            color: "rgba(255,255,255,0.82)",
            fontSize: 18,
            lineHeight: 1.55,
            fontWeight: 400,
            maxWidth: 300,
            margin: "0 auto",
          }}
        >
          {fact.message}
        </p>
      </div>

      {/* tap hint */}
      <p
        style={{
          position: "absolute",
          bottom: 36,
          color: "rgba(255,255,255,0.35)",
          fontSize: 12,
          fontWeight: 500,
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          animation: "fade-in 1s ease both 1.2s",
        }}
      >
        Tap anywhere to continue
      </p>
    </div>
  );
}
