; EcoCharge — Raspberry Pi Pico sensor reader
; Reads SW2 and SW4 analog sensors, sends over UART0 to ESP32

[env:rpipico]
platform = raspberrypi
board     = rpipico
framework = arduino

monitor_speed  = 115200
upload_speed   = 115200
