; EcoCharge — Raspberry Pi Pico sensor reader
; Reads SW2 and SW4 analog sensors, sends over UART0 to ESP32

[env:rpipico]
platform     = https://github.com/maxgerhardt/platform-raspberrypi.git
board        = rpipico
framework    = arduino
board_build.core = earlephilhower
upload_protocol  = msd

monitor_speed = 115200
